openapi: 3.0.3
info:
  title: Swagger HeartBeat API - OpenAPI 3.0
  description: |-
    This is a heart beat API to track Power Outages<br>
    <br>
    TODO: remove from here below<br>
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://127.0.0.1:13578
tags:
  - name: heartbeat
    description: Outage Monitor
    externalDocs:
      description: See here
      url: http://swagger.io
paths:
  /heartbeat:
    
    post:
      tags:
        - heartbeat
      summary: Add a new heartbeat
      description: Add a new heartbeat
      operationId: addHeartbeat
      requestBody:
        description: Create a new heartbeat
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Heartbeat'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Heartbeat'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /heartbeat/{heartbeatId}:
    get:
      tags:
        - heartbeat
      summary: Find heartbeat by ID
      description: Returns a single heartbeat
      operationId: getHeartbeatById
      parameters:
        - name: heartbeatId
          in: path
          description: ID of heartbeat to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Heartbeat'
        '400':
          description: Invalid ID supplied
        '404':
          description: Heartbeat not found
    put:
      tags:
        - heartbeat
      summary: Update an existing heartbeat
      description: Update an existing heartbeat by Id
      operationId: updateHeartbeat
      parameters:
        - name: heartbeatId
          in: path
          description: ID of heartbeat to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existent heartbeat
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Heartbeat'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Heartbeat'
        '400':
          description: Invalid ID supplied
        '404':
          description: Heartbeat not found
        '422':
          description: Validation exception
    delete:
      tags:
        - heartbeat
      summary: Deletes a heartbeat
      description: delete a heartbeat
      operationId: deleteHeartbeat
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: heartbeatId
          in: path
          description: Heartbeat id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid heartbeat value
components:
  schemas:
    Heartbeat:
      required:
        - home_nickname
        - home_name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        home_nickname:
          type: string
          example: ccc
        home_name:
          type: string
          example: My House
        last_beat_date:
          type: string
          format: date-time
          example: "2024-08-03 16:00:05"
  requestBodies:
    Heartbeat:
      description: Heartbeat object to track last time there was power
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Heartbeat'